# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20171113_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='photo',
        ),
        migrations.AddField(
            model_name='performance',
            name='photo_v',
            field=models.ImageField(blank=True, help_text='Please upload vertical photo.', null=True, upload_to='photos/'),
        ),
    ]
