# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_auto_20171212_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='photo_h',
            field=models.ImageField(blank=True, help_text='Please upload horizontal photo. This photo display at performance detail page.', null=True, upload_to='photos/'),
        ),
    ]
