# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_performance_photo_h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='actors',
            field=models.ManyToManyField(related_name='performance_actor', to='actor.Actor', verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.TimeField(verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='photo_h',
            field=models.ImageField(blank=True, help_text='Эта фотография будет отображаться на странице о спектакле.', null=True, upload_to='photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='photo_v',
            field=models.ImageField(blank=True, help_text='Эта фотография будет отображаться на главной странице.', null=True, upload_to='photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='producer',
            field=models.ManyToManyField(related_name='performance_producer', to='actor.Actor', verbose_name='Продюсер'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='sort_description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
    ]
