# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20180108_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Длительность'),
        ),
    ]
