# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20180108_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='photo_h',
            field=models.ImageField(blank=True, help_text='Эта фотография будет отображаться на странице о спектакле (соотношение ширины и высоты: 3*1, размер не более 1mb)', null=True, upload_to='photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='photo_v',
            field=models.ImageField(blank=True, help_text='Эта фотография будет отображаться на главной странице (соотношение ширины и высоты: 3*2, размер не более 1mb)', null=True, upload_to='photos/', verbose_name='Фотография'),
        ),
    ]
