# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_auto_20180218_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='performance',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
