# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 13:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='О театре')),
                ('author_description', models.TextField(verbose_name='Режиссер театра Алексей Райт')),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15, verbose_name='Телефон'), size=None)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=55, verbose_name='Адрес')),
                ('address_name', models.CharField(max_length=55, verbose_name='Название здания')),
                ('ticket_window', models.CharField(max_length=55, verbose_name='Касса работает')),
                ('facebook_link', models.URLField(max_length=55, verbose_name='Facebook')),
                ('vk_link', models.URLField(max_length=55, verbose_name='Vk')),
                ('instagram_link', models.URLField(max_length=55, verbose_name='Instagram')),
            ],
        ),
    ]
