# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 16:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='theater/'), blank=True, null=True, size=8, verbose_name='Фотографии'),
        ),
    ]
