# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdt', '0002_theater_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='photos',
        ),
        migrations.AddField(
            model_name='theater',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='theater/'),
        ),
        migrations.AddField(
            model_name='theater',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='theater/'),
        ),
        migrations.AddField(
            model_name='theater',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='theater/'),
        ),
        migrations.AddField(
            model_name='theater',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='theater/'),
        ),
        migrations.AddField(
            model_name='theater',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='theater/'),
        ),
        migrations.AddField(
            model_name='theater',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='theater/'),
        ),
        migrations.AddField(
            model_name='theater',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='theater/'),
        ),
        migrations.AddField(
            model_name='theater',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='theater/'),
        ),
    ]
