# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdt', '0003_auto_20180218_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='theater/', verbose_name='Фотография 1'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='theater/', verbose_name='Фотография 2'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='theater/', verbose_name='Фотография 3'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='theater/', verbose_name='Фотография 4'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='theater/', verbose_name='Фотография 5'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='theater/', verbose_name='Фотография 6'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='theater/', verbose_name='Фотография 7'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='theater/', verbose_name='Фотография 8'),
        ),
    ]
