# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdt', '0004_auto_20180218_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='short_name',
            field=models.CharField(default='МДТ', max_length=50, verbose_name='Короткое название'),
        ),
    ]
