# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdt', '0006_auto_20180218_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Краткое название'),
        ),
    ]
