# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_auto_20171111_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='actor',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(help_text='(соотношение ширины и высоты: 3*2, размер не более 1mb)', upload_to='photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='position',
            field=models.CharField(blank=True, help_text='Это поле не обязательное', max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
